backend = "glx";
vsync = true;

# Rounded Corners (to match your SwayFX 10px)
corner-radius = 10;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

# Shadows (to match your 0.5 opacity/20 radius)
shadow = true;
shadow-radius = 20;
shadow-opacity = 0.5;
shadow-offset-x = -20;
shadow-offset-y = -20;
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Polybar'"
];

# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
