# --------------------------------------------------------------------------
# 1. ARCHITECTURE & OPTIMIZATION
# --------------------------------------------------------------------------
CFLAGS="-march=znver3 -O2 -pipe"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"

RUSTFLAGS="-C target-cpu=znver3"

LLVM_TARGETS="X86"

# --------------------------------------------------------------------------
# 2. PARALLELISM (6 Cores / 12 Threads)
# --------------------------------------------------------------------------
MAKEOPTS="-j12 -l11"
EMERGE_DEFAULT_OPTS="--jobs 2 --load-average=10"
EMERGE_NICENESS=19
OFFLINE_PROTOCOLS="https"

# --------------------------------------------------------------------------
# 3. USE FLAGS (Hardware & Gaming Optimization)
# --------------------------------------------------------------------------
USE="X dbus udev policykit crypt cgroups pam -systemd grub elogind"
USE="${USE} X qt5 qt6 wayland gtk"
USE="${USE} cups bluetooth"
USE="${USE} pipewire jack alsa midi realtime threadsafe opus aac mp3 flac vorbis networkmanager"
USE="${USE} egl gles2 screencast libinput opengl vulkan opencl nvidia nvenc"
USE="${USE} modules-sign man secureboot"
USE="${USE} cli verify-sig unicode ipc native-symlinks"
USE="${USE} gamemode vkd3d-proton"
USE="${USE} sdl vkd3d faudio gstreamer lcms udisks threads"

ABI_X86="64 32"

CPU_FLAGS_X86="aes avx avx2 bmi1 bmi2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 vpclmulqdq"

# --------------------------------------------------------------------------
# 4. HARDWARE DRIVERS
# --------------------------------------------------------------------------
VIDEO_CARDS="nvidia"
INPUT_DEVICES="libinput"
GRUB_PLATFORMS="efi-64"

# --------------------------------------------------------------------------
# 5. PORTAGE FEATURES & CACHE
# --------------------------------------------------------------------------
FEATURES="ccache parallel-fetch collision-protect candy"
CCACHE_DIR="/var/cache/ccache"
CCACHE_SIZE="20G"
PORTAGE_TMPDIR="/var/tmp/portage"
PORTAGE_ELOG_CLASSES="warn error log"
PORTAGE_ELOG_SYSTEM="save"

# --------------------------------------------------------------------------
# 6. LICENSES & KEYWORDS
# --------------------------------------------------------------------------
ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="*"

MODULES_SIGN_KEY="/kernel_key.pem"
MODULES_SIGN_HASH="sha512"

SECUREBOOT_SIGN_KEY="/etc/secureboot/db.key"
SECUREBOOT_SIGN_CERT="/etc/secureboot/db.crt"

LINGUAS="en tr"
L10N="en tr"

