[IU]
source            = maildir://~/mail/ist-edu-msy
outgoing          = smtps://msyavuz%40istanbul.edu.tr@smtp.gmail.com:465
source-cred-cmd   = pass mail/ist-edu-msy
outgoing-cred-cmd = pass mail/ist-edu-msy
from              = Mehmet Selim Yavuz <msyavuz@istanbul.edu.tr>
copy-to           = [Gmail]/Sent Mail
folders-map       = ~/dotfiles/aerc/folders-iu.map
template-dirs     = ~/dotfiles/aerc/templates
signature-file    = ~/dotfiles/aerc/templates/academic
index-format      = notmuch://~/mail/ist-edu-msy
check-mail        = 1m
check-mail-cmd    = notmuch new

[MSY]
source            = maildir://~/mail/gmail-phd
outgoing          = smtps://mselim.yavuz.phd%40gmail.com@smtp.gmail.com:465
source-cred-cmd   = pass mail/gmail-phd
outgoing-cred-cmd = pass mail/gmail-phd
from              = "Mehmet Selim Yavuz, PhD" <mselim.yavuz.phd@gmail.com>
copy-to           = [Gmail]/Sent Mail
folders-map       = ~/dotfiles/aerc/folders-msy.map
template-dirs     = ~/dotfiles/aerc/templates
signature-file    = ~/dotfiles/aerc/templates/academic
index-format      = notmuch://~/mail/gmail-phd
check-mail        = 1m
check-mail-cmd    = notmuch new

[MAUN]
source            = maildir://~/mail/marmara
outgoing          = smtps://selim.yavuz%40marmara.edu.tr@smtp.marmara.edu.tr:465
source-cred-cmd   = pass mail/marmara
outgoing-cred-cmd = pass mail/marmara
from              = "Dr. Öğr. Üyesi Mehmet Selim Yavuz" <selim.yavuz@marmara.edu.tr>
archive           = Archive
copy-to           = Sent
postpone          = Drafts
template-dirs     = ~/dotfiles/aerc/templates
signature-file    = ~/dotfiles/aerc/templates/academic
index-format      = notmuch://~/mail/marmara
check-mail        = 1m
check-mail-cmd    = notmuch new

